[package]
authors = ["B. Blechschmidt"]
edition = "2021"
name = "tun2proxy"
version = "0.1.7"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
base64 = { version = "0.21" }
clap = { version = "4.4", features = ["derive"] }
ctrlc = "3.4"
digest_auth = "0.3"
dotenvy = "0.15"
env_logger = "0.10"
hashlink = "0.8"
httparse = "1.8"
libc = "0.2"
log = "0.4"
mio = { version = "0.8", features = ["os-poll", "net", "os-ext"] }
nix = { version = "0.27", features = [
    "process",
    "signal",
    "fs",
    "mount",
    "user",
] }
prctl = "1.0"
smoltcp = { version = "0.10", features = ["std", "phy-tuntap_interface"] }
socks5-impl = { version = "0.5", default-features = false }
thiserror = "1.0"
trust-dns-proto = "0.23"
unicase = "2.7"
url = "2.4"

[target.'cfg(target_family="unix")'.dependencies]
fork = "0.1"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13"
jni = { version = "0.21", default-features = false }

[dev-dependencies]
ctor = "0.2"
reqwest = { version = "0.11", default-features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
serial_test = "2.0"
test-log = "0.2"
